// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDo.API.DbContexts;

#nullable disable

namespace ToDo.API.Migrations
{
    [DbContext(typeof(ToDoTasksContext))]
    [Migration("20240717134620_InitialDataSeed")]
    partial class InitialDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ToDo.API.Entities.ToDoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ToDoTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = true,
                            Description = "Description11",
                            DueDate = new DateTime(2024, 7, 18, 15, 46, 20, 141, DateTimeKind.Local).AddTicks(5512),
                            Priority = 0,
                            Title = "Title1"
                        },
                        new
                        {
                            Id = 2,
                            Completed = false,
                            Description = "Description22",
                            DueDate = new DateTime(2024, 7, 19, 15, 46, 20, 141, DateTimeKind.Local).AddTicks(5561),
                            Priority = 1,
                            Title = "Title2"
                        },
                        new
                        {
                            Id = 3,
                            Completed = true,
                            Description = "Description33",
                            DueDate = new DateTime(2024, 7, 20, 15, 46, 20, 141, DateTimeKind.Local).AddTicks(5564),
                            Priority = 2,
                            Title = "Title3"
                        },
                        new
                        {
                            Id = 4,
                            Completed = false,
                            Description = "Description44",
                            DueDate = new DateTime(2024, 7, 21, 15, 46, 20, 141, DateTimeKind.Local).AddTicks(5566),
                            Priority = 0,
                            Title = "Title4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
